# Generated by Django 3.2.12 on 2022-04-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.TextField(null=True)),
                ('is_admin', models.BooleanField()),
                ('code_name', models.TextField()),
                ('user_name', models.TextField()),
                ('grade', models.TextField()),
                ('link', models.TextField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('category', models.TextField()),
                ('is_active', models.BooleanField()),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'programs',
            },
        ),
    ]
